#!/bin/bash

brew cask install virtualbox
brew install kubernetes-cli
brew cask install minikube
minikube start
kubectl apply -f ingress-nginx-controller.yaml
minikube addons enable ingress
minikube addons enable metrics-server
