#!/bin/bash

curl -sSL get.docker.com | sh && sudo usermod pi -aG docker
echo "\ncgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1" | sudo tee /boot/cmdline.txt
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list && sudo apt-get update -q && sudo apt-get install -qy kubeadm 
